apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-reader
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
#kubectl create clusterrolebinding read --clusterrole=service-reader --serviceaccount=default:default