apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: web-deployment 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      volumes: 
      - name: nginx-volume 
        persistentVolumeClaim: 
          claimName: nginx-pvc 
          readOnly: false 
      containers: 
      - image: nginx 
        imagePullPolicy: IfNotPresent 
        name: web-app 
        ports: 
        - containerPort: 80 
          protocol: TCP 
        volumeMounts: 
        - mountPath: /usr/share/nginx/html 
          name: nginx-volume 
